build: copy

dependencies:
	build:
		shc: 3.9
		g++: 5.4
		Luhm: 1.0
	runtime:
		curl: 7.47
		Luhn: 1.0
	test:
		bats: 1.0

targets:
	default:
		name: copy
		user: root
		steps:
			- mkdir -p usr/bin/
			- cp -f main.sh usr/bin/jarnik
			- cp -Rf commands usr/bin/.jarnik
			- chmod +x -R usr/bin/jarnik usr/bin/.jarnik
