#!/bin/sh

: "
Jarník Build System [JBS]

Syntax:
	jarnik command [parameters]

Commands:
	build		Builds repositories in the current project.
	clean		Removes the legos in the project.
	deploy		Deploys legos from the current project to a cloud environment.
	exec		Runs a command over the repositories in the current project.
	help		Shows this message or provide detailed help for an specific command.
	import		Clones a repository.
	list		Lists details about current project.
	mst			Minimun Spanning Tree
	new			Creates a new project with basic structure.
	post		Posts a new code review.
	release		Build + Test + Deploy
	remove		Removes repositories from the current project.
	sanitize	Sanitizes the source code.
	test		Performs unit testing for repositories in the current project.
	unlink		Unlinks cloud environments.
	version		Shows the current JBS version.
	wtf			Checks format of the source code.

	install		Installs JBS.
	setup		Set up JBS configuration.
	uninstall	Uninstalls JBS.
	upgrade		Upgrades JBS.

For further information run:
	jarnik help <command>

: "

. $jarnikdir/.core

command=$jarnikdir/$1
if [ $# -eq 0 ] || [ ! -x "$command" ] || echo "$command" | grep -Eq '/\.[^/]+$' ; then
	command=$0
fi

sed -n '/^: "$/,/^: "$/p' $command | sed -r '1,1d;$d;s/\\(.)/\1/g'
